AWS_ACCESS_KEY_ID = "TEST"
AWS_SECRET_ACCESS_KEY = "TEST"
AWS_STORAGE_BUCKET_NAME = "TEST"
AWS_S3_ENDPOINT_URL = "https://TEST1"
AWS_AUTO_CREATE_BUCKET = True
AWS_QUERYSTRING_AUTH = False
S3_BROWSER_SETTINGS = "djangoS3Browser"
TEMPLATES = [{ 'OPTIONS': {'libraries': {'s3-load': 'djangoS3Browser.templatetags.s3-tags',},}}]
SECRET_KEY = 'TEST'
DEBUG = True
ALLOWED_HOSTS = ['*']
ROOT_URLCONF= 'djangoS3Browser.s3_browser.urls'
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
STATIC_URL = '{}/static/'.format(AWS_S3_ENDPOINT_URL)
STATIC_ROOT = '/static/'
